cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name
credentials:
  usernames:
    eneas:
      email: eneas@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Eneas
      password: '53019'

oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com